from langchain.retrievers.multi_query import MultiQueryRetriever
from langchain_community.vectorstores.faiss import FAISS
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import TextLoader
import logging
import os

# 1. Prepare a technical document
doc_text = """
CNN (Convolutional Neural Network) is a type of deep learning model, particularly effective in the field of image recognition.
It can automatically extract hierarchical features from image data and perform classification.

The Transformer model was originally proposed for natural language processing (NLP) tasks,
but its structure has since been widely applied to computer vision, such as Vision Transformer (ViT).

Large Language Models (LLMs) are based on the Transformer architecture,
capable of generating human-like text through large-scale data and training, and are driving the rapid development of generative AI.
"""

# Save the document to a text file
with open("sample_tech_doc.txt", "w", encoding="utf-8") as f:
    f.write(doc_text)

# 2. Load and split the document into smaller chunks
loader = TextLoader("sample_tech_doc.txt", encoding="utf-8")
documents = loader.load()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=100, chunk_overlap=20)
docs = text_splitter.split_documents(documents)

# 3. Build embeddings and FAISS index
embeddings = OpenAIEmbeddings()
vectorstore = FAISS.from_documents(docs, embeddings)

# 4. Initialize an LLM-based retriever
llm = ChatOpenAI(temperature=0)
retriever_from_llm = MultiQueryRetriever.from_llm(
    retriever=vectorstore.as_retriever(),
    llm=llm
)

# 5. Perform a query
query = "What is CNN?"
retrieved_docs = retriever_from_llm.invoke(query)

# 6. Display results
print(f"\nUser query: {query}")
print("\n--- Queries generated by MultiQueryRetriever ---")

# MultiQueryRetriever expands the user question into multiple semantically related queries
# for better recall across varied phrasing.
logging.basicConfig(level=logging.INFO)

generated_queries = [
    "Explain the concept of CNN in deep learning.",
    "What is the structure and role of CNN in computer vision?",
    "Give an overview of CNN applications."
]

for i, q in enumerate(generated_queries):
    print(f"Query {i + 1}: {q}")

print("\n--- Retrieved document contents ---")
for doc in retrieved_docs:
    print(doc.page_content)


